# -*- coding: utf-8 -*-
"""CE888 - Lab 6 - Task 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19iK8m4-lEVtAwBfCRMeaPF3Q4ArRJBgi
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn import cluster, datasets, metrics
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

URL = "https://raw.githubusercontent.com/sagihaider/CE888_2021/main/Lab_6/Data/Country-data.csv"
URL2 = "https://raw.githubusercontent.com/sagihaider/CE888_2021/main/Lab_6/Data/data-dictionary.csv"

df = pd.read_csv(URL)
df

df1 = pd.read_csv(URL2)
df1

# Fetch data into x and y variables
x=df.iloc[:, 9:10] # Covariates or input
y=df.iloc[:,:1] # Labels or classes or output
print(x.columns)
print(y.columns)

x = x.values
y = y.values

y.shape

y = y.flatten()

y.shape

x = x.flatten()

x.shape

x

#### Cluster the data using K mean algorithm 

km=cluster.KMeans(n_clusters=3)
km.fit(df.iloc[:,1:])
km.labels_

"""## Countries clustered based on GDP per Capita using KMeans clustering 
### 0 = Developed
###1 = Under-developing countries 
###  2 = Developed countries 

"""

#Developed countries as clustered by kmeans clustering in relation to GDP 
df_cluster_0 = df[(df['cluster'] == 0)]
df_cluster_0.head()

#Under-developing countries 
df_cluster_1 = df[(df['cluster'] == 1)]
df_cluster_1.head()

#developing countries 
df_cluster_2 = df[(df['cluster'] == 2)]
df_cluster_2.head()

elements_count = {}
for element in km.labels_:
   if element in elements_count:
      elements_count[element] += 1
   else:
      elements_count[element] = 1
for key, value in elements_count.items():
   print(f"{key}: {value}")

df_0 = df.sort_values('cluster')
df_0.head(60)